server:
  port: 5001
  servlet:
    session:
#      设置超时时间为3分钟
      timeout: Pt10m

spring:
  # 10.103.238.145是云服务器
  datasource:
#    url: jdbc:mysql://localhost:3306/new_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    url: jdbc:mysql://10.103.238.145:3306/new_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: root
    password: 123456

  servlet:
     multipart:
        max-file-size: 20MB     #设置单个文件最大长度
        max-request-size: 50MB  #最大请求文件的大小
        file-size-threshold: 20MB #当文件达到多少时进行磁盘写入



#  datasource:
#   url: jdbc:mysql://localhost:3306/sjk_cu_su?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#   driver-class-name: com.mysql.cj.jdbc.Driver
#   username: root
#   password: 123456



mybatis:
  mapper-locations: classpath:Mapper/*.xml

swagger:
  enable: true

#logging:
#  level:
#    cn.jay.repository: info
#  file:
#    path: /home/jieruwang/houtaiJava/operationlogs
#    name: operation.log